name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build Expo Web
        run: bunx expo export --platform web --public-url https://sugarcypher.github.io/codex-sugar/
        
      - name: Create SPA fallback
        run: |
          # Copy index.html to 404.html for SPA routing
          cp web-build/index.html web-build/404.html
          
          # Create a proper 404.html that redirects to index.html
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <script>
              // Single Page Apps for GitHub Pages
              // https://github.com/rafgraph/spa-github-pages
              var pathSegmentsToKeep = 1;
              var l = window.location;
              l.replace(
                l.protocol + "//" + l.hostname + (l.port ? ":" + l.port : "") +
                l.pathname.split("/").slice(0, 1 + pathSegmentsToKeep).join("/") + "/?/" +
                l.pathname.slice(1).split("/").slice(pathSegmentsToKeep).join("/").replace(/&/g, "~and~") +
                (l.search ? "&" + l.search.slice(1).replace(/&/g, "~and~") : "") +
                l.hash
              );
            </script>
          </head>
          <body>
            Redirecting...
          </body>
          </html>' > web-build/404.html
          
          # Create .nojekyll file to ensure GitHub Pages serves static files correctly
          touch web-build/.nojekyll
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
