name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Export Expo Web with correct public URL
        run: |
          # Set environment variable for the public URL
          export EXPO_PUBLIC_URL=https://sugarcypher.github.io/codex-sugar
          
          # Try multiple approaches to ensure correct base href
          bunx expo export --platform web --public-url $EXPO_PUBLIC_URL
          
          echo "Exported files:"
          ls -la web-build/
        
      - name: Fix base href and create SPA fallback
        run: |
          echo "=== BEFORE FIX ==="
          echo "Current base href tags:"
          grep -n '<base href=' web-build/index.html || echo "No base tags found"
          
          # Use awk to completely rewrite the file with correct base href
          awk '
          /<head>/ { 
            print $0; 
            print "    <base href=\"/codex-sugar/\">"; 
            next 
          }
          /<base href=/ { 
            next  # Skip any existing base tags
          }
          { 
            print $0 
          }
          ' web-build/index.html > web-build/index.html.tmp && mv web-build/index.html.tmp web-build/index.html
          
          echo "=== AFTER FIX ==="
          echo "Base href after fix:"
          grep '<base href=' web-build/index.html || echo "No base href found - this is wrong!"
          
          # Verify exactly one correct base href
          base_count=$(grep -c '<base href="/codex-sugar/">' web-build/index.html || echo "0")
          echo "Correct base href count: $base_count"
          
          if [ "$base_count" -ne 1 ]; then
            echo "ERROR: Expected exactly 1 base href, found $base_count"
            exit 1
          fi
          
          # Copy index.html to 404.html for SPA routing
          cp web-build/index.html web-build/404.html
          
          # Create .nojekyll file to ensure GitHub Pages serves static files correctly
          touch web-build/.nojekyll
          
          # Inject service worker unregistration script (optional hardening)
          sed -i 's|<div id="root"></div>|<div id="root"></div>\n    <script>\n      // Unregister any existing service workers\n      if ("serviceWorker" in navigator) {\n        navigator.serviceWorker.getRegistrations().then(function(registrations) {\n          for(let registration of registrations) {\n            registration.unregister();\n          }\n        });\n      }\n    </script>|' web-build/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
