name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build for web (set public URL)
        run: bunx expo export --platform web --public-url https://sugarcypher.github.io/codex-sugar/
      - name: Inject error overlay + SPA fallback
        run: |
          set -e
          cd web-build
          cp -f index.html 404.html
          awk 'BEGIN{IGNORECASE=1}
               /<head[^>]*>/ && !injected {
                 print;
                 print "  <base href=\"/codex-sugar/\">";
                 print "  <style>#__err{position:fixed;inset:0;background:#111;color:#f55;font:14px/1.5 -apple-system,system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;padding:16px;white-space:pre-wrap;overflow:auto;display:none;}</style>";
                 print "  <script>(function(){function sh(t){var d=document.getElementById(\"__err\");if(!d){d=document.createElement(\"pre\");d.id=\"__err\";document.body.appendChild(d);}d.style.display=\"block\";d.textContent=t;}window.addEventListener(\"error\",function(e){sh(String(e.error||e.message||e).slice(0,5000));});window.addEventListener(\"unhandledrejection\",function(e){sh(\"Promise rejection: \"+String(e.reason).slice(0,5000));});})();</script>";
                 injected=1; next
               }
               { print }' index.html > index.tmp && mv index.tmp index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web-build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
