name: Deploy Expo Web to GitHub Pages - Main

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: |
          bun install
          
          echo "=== EXPO VERSION INFO ==="
          bunx expo --version
          bunx expo --help | head -20
          
          echo "=== AVAILABLE EXPO COMMANDS ==="
          bunx expo --help | grep -E "(export|build|web)" || echo "No export/build commands found"
        
      - name: Export Expo Web
        run: |
          # Check current directory and list files
          echo "=== CURRENT DIRECTORY ==="
          pwd
          ls -la
          
          # Check if web-build directory exists
          if [ -d "web-build" ]; then
            echo "web-build directory already exists, removing..."
            rm -rf web-build
          fi
          
          # Use the correct command for this Expo version
          echo "=== USING CORRECT EXPO COMMAND ==="
          echo "Expo version: $(bunx expo --version)"
          echo "Using: expo export:web"
          
          # Export web build
          bunx expo export:web
          
          echo "=== EXPORTED FILES ==="
          ls -la
          if [ -d "web-build" ]; then
            ls -la web-build/
          else
            echo "web-build directory not found!"
            # Check for other possible output directories
            echo "Checking for other output directories..."
            ls -la | grep -E "(dist|build|out|web)"
          fi
          
          # Verify the export worked
          if [ -f "web-build/index.html" ]; then
            echo "=== INDEX.HTML CONTENT ==="
            cat web-build/index.html
          else
            echo "ERROR: index.html not found after export"
            echo "Available files:"
            find . -name "*.html" -o -name "index.*" 2>/dev/null || echo "No HTML files found"
            exit 1
          fi
        
      - name: Fix base href and create SPA fallback
        run: |
          echo "=== BEFORE FIX ==="
          echo "Current base href tags:"
          grep -n '<base href=' web-build/index.html || echo "No base tags found"
          
          # Use a more robust approach that works on Ubuntu
          # Create a temporary file with the correct content
          awk '
          /<head>/ { 
            print $0; 
            print "    <base href=\"/codex-sugar/\">"; 
            next 
          }
          /<base href=/ { 
            next  # Skip any existing base tags
          }
          { 
            print $0 
          }
          ' web-build/index.html > web-build/index.html.new
          
          # Replace the original file
          mv web-build/index.html.new web-build/index.html
          
          echo "=== AFTER FIX ==="
          echo "Base href after fix:"
          grep '<base href=' web-build/index.html || echo "No base href found - this is wrong!"
          
          # Verify exactly one correct base href
          base_count=$(grep -c '<base href="/codex-sugar/">' web-build/index.html || echo "0")
          echo "Correct base href count: $base_count"
          
          if [ "$base_count" -ne 1 ]; then
            echo "ERROR: Expected exactly 1 base href, found $base_count"
            exit 1
          fi
          
          # Copy index.html to 404.html for SPA routing
          cp web-build/index.html web-build/404.html
          
          # Create .nojekyll file to ensure GitHub Pages serves static files correctly
          touch web-build/.nojekyll
          
          # Inject service worker unregistration script (optional hardening)
          sed -i 's|<div id="root"></div>|<div id="root"></div>\n    <script>\n      // Unregister any existing service workers\n      if ("serviceWorker" in navigator) {\n        navigator.serviceWorker.getRegistrations().then(function(registrations) {\n          for(let registration of registrations) {\n            registration.unregister();\n          }\n        });\n      }\n    </script>|' web-build/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
