name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Export Expo Web with correct public URL
        run: bunx expo export --platform web --public-url https://sugarcypher.github.io/codex-sugar/
        
      - name: Ensure correct base href and create SPA fallback
        run: |
          # Ensure exactly one correct base href (idempotent)
          if grep -q '<base href=' web-build/index.html; then
            # Remove any existing base tags
            sed -i '/<base href=/d' web-build/index.html
          fi
          
          # Insert correct base href after <head> tag
          sed -i 's|<head>|<head>\n    <base href="/codex-sugar/">|' web-build/index.html
          
          # Copy index.html to 404.html for SPA routing
          cp web-build/index.html web-build/404.html
          
          # Create .nojekyll file to ensure GitHub Pages serves static files correctly
          touch web-build/.nojekyll
          
          # Inject service worker unregistration script (optional hardening)
          sed -i 's|<div id="root"></div>|<div id="root"></div>\n    <script>\n      // Unregister any existing service workers\n      if ("serviceWorker" in navigator) {\n        navigator.serviceWorker.getRegistrations().then(function(registrations) {\n          for(let registration of registrations) {\n            registration.unregister();\n          }\n        });\n      }\n    </script>|' web-build/index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
