name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build for web
        run: bunx expo export --platform web

      - name: Fix base paths for GitHub Pages
        run: |
          cd web-build
          # inject <base href="/codex-sugar/"> into <head>
          awk 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print; print "  <base href=\"/codex-sugar/\">"; next} {print}' index.html > index.tmp && mv index.tmp index.html
          # rewrite absolute / URLs to /codex-sugar/ (href/src)
          find . -type f -name "*.html" -o -name "*.js" -o -name "*.css" | xargs sed -i 's|href="/|href="/codex-sugar/|g'
          find . -type f -name "*.html" -o -name "*.js" -o -name "*.css" | xargs sed -i 's|src="/|src="/codex-sugar/|g'
          # SPA fallback so deep links work
          cp -f index.html 404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web-build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
