name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build for web (set public URL)
        run: bunx expo export --platform web --public-url https://sugarcypher.github.io/codex-sugar/
      - name: Force correct base href + SPA fallback
        run: |
          cd web-build
          # remove all <base> tags
          sed -i '/<base href=/d' index.html
          # inject exactly one clean base
          awk 'BEGIN{IGNORECASE=1} /<head[^>]*>/ && !done { print; print "  <base href=\"/codex-sugar/\">"; done=1; next } { print }' index.html > index.tmp && mv index.tmp index.html
          cp -f index.html 404.html || true
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web-build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
